
# [colors.bright]
# black = "0x928374"
# blue = "0x83a598"
# cyan = "0x8ec07c"
# green = "0xb8bb26"
# magenta = "0xd3869b"
# red = "0xfb4934"
# white = "0xebdbb2"
# yellow = "0xfabd2f"
# 
# [colors.normal]
# black = "#1d1f21"
# blue = "#83a598"
# cyan = "#8ec07c"
# green = "#b8bb26"
# magenta = "#d3869b"
# red = "#fb4934"
# white = "#c5c8c6"
# yellow = "#fabd2f"
# 
# [colors.primary]
# background = "#000000"
# foreground = "#ebdbb2"

[cursor]
vi_mode_style = "Block"

[cursor.style]
blinking = "On"
shape = "Underline"

[env]
TERM = "alacritty"

[font]
size = 9.0

[font.bold]
family = "xos4 Terminus"
style = "Bold"

[font.bold_italic]
family = "xos4 Terminus"
style = "Bold"

[font.normal]
family = "xos4 Terminus"
style = "Medium"

[scrolling]
history = 10000
multiplier = 3

[general]
live_config_reload = true

import = [
  "~/.alacritty_gruvbox_dark.toml"
]
